#!/bin/bash

PATH=".venv/bin:$PATH"

set -ex

# format code
if [[ $CI ]]; then
    black --check .
    isort --check .
else
    black .
    isort .
fi

pyright .

# type check code
mypy tests

# lint
flake8 tests
